language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"

cache:
  yarn: true
  directories:
    - node_modules

services:
  - postgresql

jobs:
  include:
    - addons:
        postgresql: "11"
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
            - postgresql-server-dev-11
            - postgresql-client-common
            - postgresql-common
            - postgresql-11-postgis-3
            - postgresql-11-postgis-3-scripts
      env:
        PGPORT: "5433"
        PGVERSION: 11
    - addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
            - postgresql-server-dev-12
            - postgresql-client-common
            - postgresql-common
            - postgresql-12-postgis-3
            - postgresql-12-postgis-3-scripts
      env:
        PGPORT: "5433"
        PGVERSION: 12

before_install:
  - "if [ ! -z $PGVERSION ]; then sudo cp /etc/postgresql/{9.6,$PGVERSION}/main/pg_hba.conf; fi"
  - "if [ ! -z $PGVERSION ]; then sudo service postgresql restart $PGVERSION; fi"
  - sh -c 'until pg_isready -p 5433; do echo "Waiting for the DB to be up..."; sleep 2; done'
