language: node_js
node_js:
  - "10"
  - "11"
  - "12"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12 postgresql-12-postgis-3 postgresql-12-postgis-3-scripts
  - sudo cp /etc/postgresql/{9.6,11,12}/main/pg_hba.conf
  - sudo service postgresql restart 12
addons:
  postgresql: 12
env:
  global:
    - PGPORT=5432
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
