language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"

services:
  - postgresql

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
      - postgresql-12-postgis-3
      - postgresql-12-postgis-3-scripts

cache:
  yarn: true
  directories:
    - node_modules
