language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"

env:
  global:
    - PGPORT=5432

services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
      - postgresql-12-postgis-3
      - postgresql-12-postgis-3-scripts

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - sudo pg_dropcluster --stop 12 main
  - sudo pg_upgradecluster 11 main
  - sudo pg_ctlcluster 12 main restart
  - sudo pg_dropcluster 11 main

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
