os: linux
dist: bionic

language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"

services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_install:
  - sudo pg_dropcluster --stop 12 main
  - sudo pg_upgradecluster 11 main
  - sudo pg_ctlcluster 12 main restart
  - sudo pg_dropcluster 11 main
env:
  global:
    - PGPORT=5432
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
