language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"

env:
  global:
    - PGPORT=5433

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
      - postgresql-12-postgis-3
      - postgresql-12-postgis-3-scripts

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
