language: node_js
sudo: true

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - addons:
        postgresql: "11"
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
            - postgresql-server-dev-11
            - postgresql-client-common
            - postgresql-common
            - postgresql-11-postgis-3
            - postgresql-11-postgis-3-scripts
      dist: focal
      env:
        PGPORT: "5433"
        PGVERSION: 11
      node_js:
        - "12"
        - "13"
        - "14"
        - "15"
    - addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
            - postgresql-server-dev-12
            - postgresql-client-common
            - postgresql-common
            - postgresql-12-postgis-3
            - postgresql-12-postgis-3-scripts
      dist: focal
      env:
        PGPORT: "5433"
        PGVERSION: 12
      node_js:
        - "12"
        - "13"
        - "14"
        - "15"
    - addons:
        postgresql: "13"
        apt:
          packages:
            - postgresql-13
            - postgresql-client-13
            - postgresql-server-dev-13
            - postgresql-client-common
            - postgresql-common
            - postgresql-13-postgis-3
            - postgresql-13-postgis-3-scripts
      dist: focal
      env:
        PGPORT: "5433"
        PGVERSION: 13
      node_js:
        - "12"
        - "13"
        - "14"
        - "15"

before_install:
  - sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD null"
  - sudo -u postgres psql -c "ALTER ROLE postgres SUPERUSER"
